### ISSUE TITLE
'/static/' path not found when running wsgi on apache

### ISSUE THREAD

**Issue by smacz42** [bartromgens/bitcoinnodestats#4]
The CSS and JS are only called by Apache's `mod_wsgi` when the `${PWD}/bitcoinnodestats/static` directory is moved up to `${PWD}/static`.

EDIT: It works fine when using Django, just not Apache.

**Comment by smacz42** [comment]
Apache config error. Closing.

For reference, a known-good config is:

```
# WSGI
WSGIScriptAlias /bu-node /srv/httpd/bitcoinnodestats/bitcoinnodestats/wsgi.py
WSGIPythonHome /srv/httpd/bitcoinnodestats/env
WSGIPythonPath /srv/httpd/bitcoinnodestats

<VirtualHost _default_:443>

DocumentRoot /srv/httpd/bitcoinnodestats

Alias /media/ /srv/httpd/bitcoinnodestats/bitcoinnodestats/static/media/
Alias /static/ /srv/httpd/bitcoinnodestats/bitcoinnodestats/static/

<Directory /srv/httpd/bitcoinnodestats/bitcoinnodestats/static/>
Require all granted
</Directory>

<Directory /srv/httpd/bitcoinnodestats/bitcoinnodestats/static/media/>
Require all granted
</Directory>

<Directory /srv/httpd/bitcoinnodestats>
<Files wsgi.py>
Require all granted
</Files>
</Directory>
```

**Comment by bartromgens** [comment]
When not using the Django development server, you typically have to set the `STATIC_ROOT` in `bitcoinnodestats/local_settings.py`, and run `python manage.py collectstatic` to move the static files to that location, then serve these via Apache. 

Your solution also works! Thanks for sharing a working Apache config.
