### ISSUE TITLE
Support for Django 2.2+

### ISSUE THREAD

**Issue by knobix** [bartromgens/bitcoinnodestats#5]
Django 1.11 is End-Of-Life since April 2020 and Django 2.2 is the current LTS release. 

I tried to run bitcoinnodestats with Django 2.2 and Python 3.7 but it fails if started with `python3.7 manage.py runserver`. I can supply the backtrace if requested.

Are there any plans to adapt the project for newer Django versions?

**Comment by bartromgens** [comment]
@knobix This is a small old project that I don't plan to update or maintain. Sorry. I will edit the readme to make this clear.

**Comment by knobix** [comment]
@bartromgens No problem, thank you for the quick feedback. I close this issue then.
